[2014-08-15 14:45:02.611] [INFO] log - server pid: 5712
[2014-08-15 14:45:14.992] [ERROR] log - { [Error: ENOENT, open 'E:\wangjh\APP\public\PASSWORD_RESET_EMAIL.html']
  errno: 34,
  code: 'ENOENT',
  path: 'E:\\wangjh\\APP\\public\\PASSWORD_RESET_EMAIL.html' }
Error: ENOENT, open 'E:\wangjh\APP\public\PASSWORD_RESET_EMAIL.html'
[2014-08-15 14:45:37.904] [INFO] log - server pid: 5488
[2014-08-15 14:45:38.043] [INFO] log - server pid: 6048
[2014-08-15 14:45:44.903] [ERROR] log - { [Error: ENOENT, open 'E:\public\PASSWORD_RESET_EMAIL.html']
  errno: 34,
  code: 'ENOENT',
  path: 'E:\\public\\PASSWORD_RESET_EMAIL.html' }
Error: ENOENT, open 'E:\public\PASSWORD_RESET_EMAIL.html'
[2014-08-15 14:46:02.005] [INFO] log - server pid: 4884
[2014-08-15 14:46:02.014] [INFO] log - server pid: 4592
[2014-08-15 14:50:42.944] [INFO] log - server pid: 4264
[2014-08-15 14:50:43.302] [INFO] log - server pid: 5740
[2014-08-15 14:51:44.762] [ERROR] log - { [HttpError: The credentials provided are invalid]
  _isError: true,
  name: 'HttpError',
  httpCode: 403,
  restCode: 'InvalidCredentials',
  message: 'The credentials provided are invalid',
  cause: [Error: no object] }
HttpError: The credentials provided are invalid
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:221:17)
    at RestClient.post (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:201:12)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
    at TCP.onread (net.js:404:27)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 14:53:05.683] [ERROR] log - { [HttpError: The credentials provided are invalid]
  _isError: true,
  name: 'HttpError',
  httpCode: 403,
  restCode: 'InvalidCredentials',
  message: 'The credentials provided are invalid',
  cause: [Error: no object] }
HttpError: The credentials provided are invalid
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:221:17)
    at RestClient.post (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:201:12)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
    at TCP.onread (net.js:404:27)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 14:54:18.456] [INFO] log - server pid: 3844
[2014-08-15 14:54:18.476] [INFO] log - server pid: 3224
[2014-08-15 14:54:57.345] [INFO] log - server pid: 5548
[2014-08-15 14:54:57.435] [INFO] log - server pid: 4572
[2014-08-15 16:39:59.160] [INFO] log - server pid: 668
[2014-08-15 16:39:59.228] [INFO] log - server pid: 5260
